import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Student, Subject, CalculationResult } from '../types';
import { GRADE_SCALE } from './gradeCalculations';

export const exportToPDF = (
  student: Student,
  result: CalculationResult,
  previousSemesters: any[]
) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(59, 130, 246); // Blue color
  doc.text('GradeCalcPro - Academic Report', 105, 20, { align: 'center' });
  
  // Student Information
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Student Information', 20, 40);
  
  doc.setFontSize(12);
  doc.text(`Name: ${student.name}`, 20, 55);
  doc.text(`USN: ${student.usn}`, 20, 65);
  doc.text(`Semester: ${student.semester}`, 20, 75);
  
  // Subjects Table
  const tableData = result.subjects.map(subject => [
    subject.name,
    subject.credits.toString(),
    subject.internalMarks.toString(),
    subject.estimatedExternalMarks?.toString() || 'N/A',
    subject.totalMarks?.toFixed(1) || 'N/A',
    subject.grade || 'N/A',
    subject.gradePoints?.toString() || 'N/A'
  ]);
  
  autoTable(doc, {
    head: [['Subject', 'Credits', 'Internal', 'Est. External', 'Total %', 'Grade', 'Points']],
    body: tableData,
    startY: 85,
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
  });
  
  // Results
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(14);
  doc.text('Results', 20, finalY);
  
  doc.setFontSize(12);
  doc.text(`SGPA: ${result.sgpa.toFixed(2)}`, 20, finalY + 15);
  if (result.cgpa) {
    doc.text(`CGPA: ${result.cgpa.toFixed(2)}`, 20, finalY + 25);
  }
  doc.text(`Total Credits: ${result.totalCredits}`, 20, finalY + 35);
  
  // Note
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Note: Results based on minimum external marks required to pass (35/100)', 20, finalY + 50);
  
  // Footer
  doc.text('Generated by GradeCalcPro', 105, 280, { align: 'center' });
  
  doc.save(`${student.name}_${student.usn}_Semester_${student.semester}.pdf`);
};